Traceback (most recent call last):
  File "/home/mc35291/repo/attn_code/loss_mo/main.py", line 226, in <module>
    evaluate_model(model, args)
  File "/home/mc35291/repo/attn_code/loss_mo/main.py", line 172, in evaluate_model
    test_log,preds = model(args.belief_threshold, eachbatch, bVec.to(args.device), fwd_noise_par.to(args.device), ys,isTraining=0)
UnboundLocalError: local variable 'ys' referenced before assignment
